# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
from PyQt5.QtWidgets import QLabel


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(811, 600)
        Dialog.setStyleSheet("vertical-align: middle ")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(0, 450, 180, 60))
        self.pushButton.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-size: 15pt;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 5px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 3px;")
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 450, 180, 60))
        self.pushButton_2.setStyleSheet("background: #E6E6FA; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-size: 15pt;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 5px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 3px;")
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 389, 81))
        self.textEdit.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-size: 40pt;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 5px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 3px;")
        self.textEdit.setObjectName("textEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 90, 391, 293))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_7 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_7.setEnabled(True)
        self.textEdit_7.setStyleSheet("background: #E6E6FA; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-weight: 450;\n"
"text-align: center;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"text-align:  center;")
        self.textEdit_7.setObjectName("textEdit_7")
        self.gridLayout.addWidget(self.textEdit_7, 2, 1, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_4.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-size: 40pt;\n"
"vertical-align: middle;\n"
"font-weight: 600;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"vertical-align: middle;\n"
"text-align:  center;")
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout.addWidget(self.textEdit_4, 2, 0, 1, 1)
        self.textEdit_6 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_6.setStyleSheet("background: #E6E6FA; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"vertical-align: middle;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"text-align:  center;")
        self.textEdit_6.setObjectName("textEdit_6")
        self.gridLayout.addWidget(self.textEdit_6, 1, 1, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_3.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-size: 40pt;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"vertical-align: middle;\n"
"text-align:  center;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout.addWidget(self.textEdit_3, 1, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_2.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"vertical-align: middle;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"text-align:  center;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.textEdit_5 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_5.setStyleSheet("background: #E6E6FA; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"vertical-align: middle;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"text-align:  center;")
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout.addWidget(self.textEdit_5, 0, 1, 1, 1)
        self.textEdit_8 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_8.setGeometry(QtCore.QRect(420, 0, 389, 81))
        self.textEdit_8.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-size: 40pt;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 5px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 3px;")
        self.textEdit_8.setObjectName("textEdit_8")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(420, 90, 391, 293))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit_9 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_9.setEnabled(True)
        self.textEdit_9.setStyleSheet("background: #E6E6FA; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-weight: 450;\n"
"text-align: center;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"text-align:  center;")
        self.textEdit_9.setObjectName("textEdit_9")
        self.gridLayout_2.addWidget(self.textEdit_9, 2, 1, 1, 1)
        self.textEdit_10 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_10.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-size: 40pt;\n"
"vertical-align: middle;\n"
"font-weight: 600;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"vertical-align: middle;\n"
"text-align:  center;")
        self.textEdit_10.setObjectName("textEdit_10")
        self.gridLayout_2.addWidget(self.textEdit_10, 2, 0, 1, 1)
        self.textEdit_11 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_11.setStyleSheet("background: #E6E6FA; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"vertical-align: middle;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"text-align:  center;")
        self.textEdit_11.setObjectName("textEdit_11")
        self.gridLayout_2.addWidget(self.textEdit_11, 1, 1, 1, 1)
        self.textEdit_12 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_12.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"font-size: 40pt;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"vertical-align: middle;\n"
"text-align:  center;")
        self.textEdit_12.setObjectName("textEdit_12")
        self.gridLayout_2.addWidget(self.textEdit_12, 1, 0, 1, 1)
        self.textEdit_13 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_13.setStyleSheet("background: #DCDCDC; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"vertical-align: middle;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"text-align:  center;")
        self.textEdit_13.setObjectName("textEdit_13")
        self.gridLayout_2.addWidget(self.textEdit_13, 0, 0, 1, 1)
        self.textEdit_14 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_14.setStyleSheet("background: #E6E6FA; /* Цвет фона */\n"
"color: #000000; /* Цвет текста */\n"
"padding: 10px; /* Поля вокруг текста */\n"
"vertical-align: middle;\n"
"vertical-align: middle;\n"
"font-weight: 450;\n"
"font-family: \"Times New Roman\", Georgia, Serif;\n"
"border-radius: 10px; /* Уголки */\n"
"border-style:solid;\n"
"border-color: #000000;\n"
"border-width: 2px;\n"
"text-align:  center;")
        self.textEdit_14.setObjectName("textEdit_14")
        self.gridLayout_2.addWidget(self.textEdit_14, 0, 1, 1, 1)

        self.thirdRow = QLabel('', Dialog)
        # self.thirdRow.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdRow.setGeometry(QtCore.QRect(510, 390, 200, 200))
        self.movie = QMovie("lib/5.gif")
        self.movie.setScaledSize(QtCore.QSize(200, 200))

        self.thirdRow.setMovie(self.movie)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CSFAIL"))
        self.pushButton.setText(_translate("Dialog", "Start"))
        self.pushButton_2.setText(_translate("Dialog", "Stop"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:40pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:28pt; font-weight:400; vertical-align:middle;\">Statistic of session</span></p></body></html>"))
        self.textEdit_7.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:8.25pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt;\"> </span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:40pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12pt; color:#000000; background-color:rgba(0,0,0,0.039216);\">evaluation of the model\'s performance %</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:8.25pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt;\"> </span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:40pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:20pt; font-weight:600; color:#000000; background-color:rgba(0,0,0,0.039216);\">win</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:8.25pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:16pt; font-weight:600; color:#000000; background-color:rgba(0,0,0,0.039216); vertical-align:middle;\">total site bank online</span></p></body></html>"))
        self.textEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:8.25pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt;\"> </span></p></body></html>"))
        self.textEdit_8.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:40pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:28pt; font-weight:400; vertical-align:middle;\">Last Game</span></p></body></html>"))
        self.textEdit_9.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:8.25pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt;\"> </span></p></body></html>"))
        self.textEdit_10.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:40pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:24pt; color:#000000; background-color:rgba(0,0,0,0.039216);\">predict</span></p></body></html>"))
        self.textEdit_11.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:8.25pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt;\"> </span></p></body></html>"))
        self.textEdit_12.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:40pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:24pt; font-weight:600; color:#000000; background-color:rgba(0,0,0,0.039216);\">bank</span></p></body></html>"))
        self.textEdit_13.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:8.25pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:24pt; font-weight:600; color:#000000; background-color:rgba(0,0,0,0.039216); vertical-align:middle;\">coeff</span></p></body></html>"))
        self.textEdit_14.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\',\'Georgia\',\'Serif\'; font-size:8.25pt; font-weight:448; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt;\"> </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
